# -*- coding: utf-8 -*-
"""Maior_Element_Pilha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kj9vnZrSyT3eMUE7KJBivwhs2SQusJRw
"""

##maior elemento da pilha
class MaiorElementoPilha:
    def __init__(self,capacidade):
        self.capacidade = capacidade
        self.pilha = []
    def empilhar(self,valor):
        pilha = self.pilha
        pilha.append(valor)
    def ver_topo(self):
        return self.pilha
    def maior(self):
        valores = self.pilha
        tamanho_pilha = len(valores)
        maior = 0
        if (tamanho_pilha == 0):
            return "Pilha Vazia."
        elif (tamanho_pilha == self.capacidade):
            print("A pilha cheia, não é possivel adicionar mais itens.")
            for itens in valores:
                valor = itens
                if valor > maior:
                    maior = itens
            print("O numero maior da pilha é:")
            return maior

pilha = MaiorElementoPilha(4)
pilha.empilhar(1)
pilha.empilhar(6)
pilha.empilhar(4)
pilha.empilhar(100)
print(pilha.maior())