# -*- coding: utf-8 -*-
"""QT_Aeroporto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18jnjSsO_PA2swJThCer5T3hyCdJtlBRF
"""

import numpy as np

##QT_Aeroporto

class Aeroporto:
    def __init__(self,capacidade):
        self.capacidade = capacidade
        self.comeco = 0
        self.fim = -1
        self. qtd_aeronaves = 0
        self.aeronaves = np.empty(self.capacidade, dtype=int)
        self.ident_letra = np.chararray(self.capacidade, itemsize=3, unicode=True)
        self.numeracao = np.chararray(self.capacidade, itemsize=4, unicode=True)

    def __fila_vazia(self):
        return self.qtd_aeronaves == 0

    def __pista_ocupada(self):
        return self.qtd_aeronaves == self.capacidade

    def fila_decolagem(self, aeronaves, ident_letra:str, numeracao):
        if self.__pista_ocupada():
            print('Aeronave na pista.')

        if self.fim == self.capacidade -1:
            self.fim = -1
        self.fim += 1
        self.aeronaves[self.fim] = aeronaves
        self.ident_letra[self.fim] = ident_letra
        self.numeracao[self.fim] = numeracao
        self.qtd_aeronaves += 1

    def pista_vazia(self):
        if self.__fila_vazia():
            print('Pista Livre')
        else:
            temp = self.aeronaves[self.comeco]
            self.comeco += 1
            if self.comeco == self.capacidade -1:
                self.comeco = 0
            else:
                self.qtd_aeronaves -= 1
                return temp

    def num_aeronaves(self):
        if self.__fila_vazia():
           return 'Sem decolagens sequentes'
        else:
            print(f'Numero de aeronaves aguardando autorização para decolar: {self.qtd_aeronaves}')

    def proxima_decolagem(self):
        if self.__fila_vazia():
            print('Pista livre, Decolagem autorizada.')
        else:
            proxima_aeronave = self.aeronaves[self.comeco]
            ident_letra_aeronave = self.ident_letra[self.comeco]
            numeracao_aeronave = self.numeracao[self.comeco]

            print(f'Aeronave {proxima_aeronave}, COD: {ident_letra_aeronave}, de Inscrição {numeracao_aeronave}: Decolagem Autorizada.')

    def listar_aeronaves(self):
        for i in range(len(self.aeronaves)):
            print(f' Aguardando Decolagem:\n Aeronave: {self.aeronaves[i]}\n')

fila = Aeroporto(5)
fila.fila_decolagem(1,'GOL', '2419')
fila.fila_decolagem(2,'AZUL', '741')
fila.fila_decolagem(3,'TAM', '1660')
fila.fila_decolagem(4,'GOL','1555')
fila.fila_decolagem(5,'TAM','3444')


fila.num_aeronaves()
fila.proxima_decolagem()
fila.listar_aeronaves()
fila.pista_vazia()
fila.num_aeronaves()